FROM  nginx:latest

#ToDo:docker-composeでボリュームをマウントする
ADD ./index.html /usr/share/nginx/html
ADD ./css /usr/share/nginx/html
ADD ./js /usr/share/nginx/html
ADD ./img /usr/share/nginx/html
ADD ./conf/default.conf /etc/nginx/conf.d/